### ISSUE TITLE
Deploy Web API on server

### ISSUE THREAD

**Issue by Pheros** [danesparza/OWIN-WebAPI-Service#5]
I have followed your tutorial and everything is working locally. 
When I try to connect to the web api remotely, I am getting this Error: TimedOut (0x274c)
The port is listening accordingly to the one defined in the application as well as the urlacl set by the netsh command. Any ideas?

**Comment by danesparza** [comment]
I haven't ever seen that before.  Some sanity checking to do:

Does this service work locally on your machine?
Are you using the same port locally as you are on the remote machine?
Have you tried using remote desktop to access the service from the service box?
Can you resolve the DNS name for the server from the client machine?
Is there a firewall or device along the network path blocking access to the TCP port on the server?

**Comment by Pheros** [comment]
The service works locally on my machine.
I am using the same address and port both locally and remotely
I am not sure about "access the service from the service box" ?
I am able to resolve the address for the machine. For the moment I have deployed the service on my local machine, that shouldn't cause any problems? 
I have talked to the network guys and we shouldn't blocked anything  inhouse.

**Comment by Pheros** [comment]
I found the error. I had to create an inbound rule in the Windows Firewall on that local port. Thanks for your time and your tutorial. Have you created any help pages of any kind within the Web API?

**Comment by danesparza** [comment]
Glad to hear it, @Pheros! 

Now, when you say 'within the Web API' do you mean documenting your API with help pages?  If so, you may be interested in [this Nuget package](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.HelpPage/5.2.3) and [this tutorial](http://www.asp.net/web-api/overview/getting-started-with-aspnet-web-api/creating-api-help-pages).  :smile:

**Comment by Pheros** [comment]
Yes :): Thanks!
