### ISSUE TITLE
Link to post on creating a custom assemblies resolver

### ISSUE THREAD

**Issue by valeriy-novytskyy** [danesparza/OWIN-WebAPI-Service#7]
Hello,

Thank you for taking the time to put together this resource. It is now popular and at the top of search results for anyone looking to host WebAPI in a Windows Service. Please consider adding a link describing how to create a custom assemblies resolver into your discussion on discovering WebAPI controllers. I really liked the following article, which is simple, works great, and even goes in depth:

http://www.strathweb.com/2013/08/customizing-controller-discovery-in-asp-net-web-api/

I think this will help anyone else who finds this repo to get started even quicker. You could even include a sample assemblies resolver. I personally never heard of this, and unfortunately there are lots of things called "assembly resolvers" which don't refer to the concept you meant. For example:

- https://msdn.microsoft.com/en-us/library/system.appdomain.assemblyresolve(v=vs.110).aspx 
- https://msdn.microsoft.com/en-us/library/ee236671(v=bts.10).aspx
- http://esb.stottcreations.com/how-to-create-a-custom-resolver/

etc..

Thank you for consideration despite an old repo.

**Comment by danesparza** [comment]
Great suggestion @valeriy-novytskyy !  I'll link to it in the readme! :star:
