### ISSUE TITLE
Add Steeltoe to OWIN-WebAPI-Service-SelfHost

### ISSUE THREAD

**Issue by gobhr** [danesparza/OWIN-WebAPI-Service#9]
Would like to see Steeltoe Service Discovery added to this project.

**Comment by danesparza** [comment]
Looks like a [proprietary service registry](https://steeltoe.io/docs/steeltoe-discovery/), is that right?  

As this is meant to be a fairly generic overview of a set of Microsoft technologies, I'm not sure how Pivotal's service directory fits in to this example.  Can you help me see something I might be missing?

**Comment by danesparza** [comment]
Closing after no reply
